version: '3.3'
services:
  nginx:
    build: 
      context: ../
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - django_static_volume:${DJANGOAPP_CONTAINER_ROOT_DIR}${DJANGOAPP_STATIC_PATH}
    ports:
      - 8000:80
    depends_on:
      - djangoapp
    stdin_open: true
    tty: true
  db:
    image: mysql:5.6
    volumes:
      - /var/lib/mysql
      - ../eshop/db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./db/init.sql:/opt/services/db/init.sql
    command: --default-authentication-plugin=mysql_native_password --init-file /opt/services/db/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 32000:3306
    stdin_open: true
    tty: true
  djangoapp:
    build: 
      context: ../
      dockerfile: docker/djangoapp/Dockerfile
      args:
        - working_dir=${DJANGOAPP_CONTAINER_ROOT_DIR}
    volumes:
      - django_volume:${DJANGOAPP_CONTAINER_ROOT_DIR}
      - django_static_volume:${DJANGOAPP_CONTAINER_ROOT_DIR}${DJANGOAPP_STATIC_PATH}
    depends_on:
      - db
    entrypoint: sh -c 'cd eshop && gunicorn --bind :8000 eshop.wsgi:application'
    stdin_open: true
    tty: true
volumes:
  django_volume:
  django_static_volume:
