# Generated by Django 2.0 on 2019-02-26 11:06

from django.db import migrations, models
import ebag.models


class Migration(migrations.Migration):

    dependencies = [
        ('ebag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=ebag.models.Product.save_file_with_id_name),
        ),
    ]
