# Generated by Django 2.0 on 2019-02-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebag', '0002_auto_20190226_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
